---
- name: Assertions for apache role
  ansible.builtin.assert:
    that:
    - __apache_conf_available_dir != None
    - __apache_conf_enabled_dir != None

# template
- name: Template configs
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ __apache_conf_available_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ apache_configs }}"
  when: item.template | length > 0
  notify: Reload apache

# enable
- name: Enable Apache configurations
  ansible.builtin.file:
    src: "{{ __apache_conf_available_dir }}/{{ item.name }}"
    dest: "{{ __apache_conf_enabled_dir }}/{{ item.name }}"
    state: link
  loop: "{{ apache_configs }}"
  when: item.state == "enabled"
  notify: Reload apache

# disable
- name: Disable Apache configurations
  ansible.builtin.file:
    path: "{{ __apache_conf_enabled_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ apache_configs }}"
  when: item.state == "disabled"
  notify: Reload apache