---
- name: apache role
  tags:
    - apache
  block:

  # load either vars/debian.yml or vars/redhat.yml
  - name: Include OS-specific variables
    ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

  # install apache
  - name: Ensure Apache is installed
    ansible.builtin.package:
      name: "{{ __apache_package }}"
      state: present

  # install packages
  - name: Install packages {{ apache_install_packages }}
    ansible.builtin.package:
      name: "{{ apache_install_packages }}"
      state: present

  # remove packages
  - name: Remove packages {{ apache_remove_packages }}
    ansible.builtin.package:
      name: "{{ apache_remove_packages }}"
      state: absent

  - ansible.builtin.import_tasks: modules.yml
  - ansible.builtin.import_tasks: configs.yml
  - ansible.builtin.import_tasks: sites.yml
