---
- name: Assertions for apache role
  ansible.builtin.assert:
    that:
    - __apache_service != None

# reset overrides
- when: apache_systemd_overrides_reset == true 
  name: Reset systemd system unit overrides {{ apache_systemd_reset }}
  become: true
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ __apache_service }}.d"
    state: absent

# overrides
- when: apache_systemd_overrides | length > 0
  block:

  # mkdir overrides
  - name: Mkdir in /etc/systemd/system/...
    become: true
    ansible.builtin.file:
      path: "/etc/systemd/system/{{ __apache_service }}.d"
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx

  # cp overrides
  - name: Copy systemd system unit overrides {{ apache_systemd_overrides }}
    become: true
    notify: systemctl --system daemon-reload
    loop: "{{ apache_systemd_overrides }}"
    ansible.builtin.copy:
      src: "{{ role_path }}/files/{{ item }}"
      dest: "/etc/systemd/system/{{ __apache_service }}.d/{{ item }}"
      force: true
      owner: root
      group: root
      mode: u=rw,g=r,o=r

# state
- name: Set state of {{ __apache_service }} (state={{ apache_systemd_state }}, enabled={{ apache_systemd_enabled }})
  become: true
  loop: "{{ apache_systemd_enable }}"
  ansible.builtin.systemd_service:
    scope: system
    name: "{{ __apache_service }}"
    state: "{{ apache_systemd_state }}"
    enabled: "{{ apache_systemd_enabled }}"
