---
- name: Restart apache
  become: true
  ansible.builtin.systemd_service:
    scope: system
    name: "{{ __apache_service }}"
    state: restarted

- name: Reload apache
  become: true
  ansible.builtin.systemd_service:
    scope: system
    name: "{{ __apache_service }}"
    state: reloaded

- name: systemctl --system daemon-reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: system